### ISSUE TITLE
赚京豆脚本报错，互助的时候提示活动火爆，跳出，导致无法成团获得成团积分。

### ISSUE THREAD

**Issue by dreamfrog7** [wisz2021/jd_docker#113]
May 09 00:12:27 ==================脚本执行- 北京时间(UTC+8)：5/9/2021, 12:12:27 AM=====================
May 09 00:12:27 
May 09 00:12:27 
May 09 00:12:27 ❗️赚京豆, 错误!
May 09 00:12:27 SyntaxError: Unexpected token < in JSON at position 0
May 09 00:12:27     at JSON.parse (<anonymous>)
May 09 00:12:27     at /scripts/jd_syj.js:716:59
May 09 00:12:27     at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/scripts/jd_syj.js:829:4869)
May 09 00:12:27     at processTicksAndRejections (internal/process/task_queues.js:93:5)
May 09 00:13:15 catch 读取邀请码异常:Timeout awaiting 'request' for 10000ms

May 09 00:37:05 内部互助 【赚京豆(微信小程序)-瓜分京豆】活动(优先内部账号互助(需内部cookie数量大于4个)，如有剩余助力次数则给作者lxk0301和随机团助力)
May 09 00:37:05 
May 09 00:37:05 开始账号内部互助 赚京豆-瓜分京豆 活动，优先内部账号互助
May 09 00:37:05 账号 justgonow 开始给 【RTYIrwj8CSmAihy9X2bwXA==
May 09 00:37:05 】助力
May 09 00:37:05 catch 赚京豆团邀请码提交异常:Response code 500 (Internal Server Error)
May 09 00:37:05 助力结果：活动火爆，跳出
May 09 00:37:05 
May 09 00:37:05 开始账号内部互助 赚京豆-瓜分京豆 活动，优先内部账号互助
May 09 00:37:05 账号 jd_CBbetQBbWxCc 开始给 【RTYIrwj8CSmAihy9X2bwXA==
May 09 00:37:05 】助力
May 09 00:37:05 助力结果：活动火爆，跳出

**Comment by start0325** [comment]
火爆一般是黑号了

**Comment by limoruirui** [comment]
> 火爆一般是黑号了

手动可以

**Comment by limoruirui** [comment]
不知道有没有办法拿到4月27号更新前的syj脚本

**Comment by dreamfrog7** [comment]
手动也不行，另外一个好像可以




在2021年05月09日 14:23，limo_ruirui 写道：

不知道有没有办法拿到4月27号更新前的syj脚本

**Comment by limoruirui** [comment]
> 火爆一般是黑号了

现在每个号都开团了 有什么方法只给前面几个号助力么

**Comment by yyetss** [comment]
> 不知道有没有办法拿到4月27号更新前的syj脚本

用了老版本确实可以了。你的宠汪汪赛跑可以助力吗。我用3月份的版本也不行

**Comment by limoruirui** [comment]
> > 不知道有没有办法拿到4月27号更新前的syj脚本
> 
> 用了老版本确实可以了。你的宠汪汪赛跑可以助力吗。我用3月份的版本也不行

宠汪汪我最近一直不行 不过这活动我不怎么在意 目前光是升级的积分都够每天换20豆子了 就没去管

**Comment by limoruirui** [comment]
> > 不知道有没有办法拿到4月27号更新前的syj脚本
> 
> 用了老版本确实可以了。你的宠汪汪赛跑可以助力吗。我用3月份的版本也不行

你现在用会赚京豆 会给其它的小号助力么 以前是只要没手动开过一次就开团失败 现在新版本每个号都给开过了 导致现在每个号都能开团 这样助力怎么都不够了

**Comment by yyetss** [comment]
> > > 不知道有没有办法拿到4月27号更新前的syj脚本
> > 
> > 
> > 用了老版本确实可以了。你的宠汪汪赛跑可以助力吗。我用3月份的版本也不行
> 
> 你现在用会赚京豆 会给其它的小号助力么 以前是只要没手动开过一次就开团失败 现在新版本每个号都给开过了 导致现在每个号都能开团 这样助力怎么都不够了

可以，开团助力都正常

**Comment by limoruirui** [comment]
> > > > 不知道有没有办法拿到4月27号更新前的syj脚本
> > > 
> > > 
> > > 用了老版本确实可以了。你的宠汪汪赛跑可以助力吗。我用3月份的版本也不行
> > 
> > 
> > 你现在用会赚京豆 会给其它的小号助力么 以前是只要没手动开过一次就开团失败 现在新版本每个号都给开过了 导致现在每个号都能开团 这样助力怎么都不够了
> 
> 可以，开团助力都正常

我是说你现在用的话 会所有号都吃到助力么 如果所有号都开团的话 最终每个号都只能成功开到一次团吧 次数不够

**Comment by yyetss** [comment]
> > > > > 不知道有没有办法拿到4月27号更新前的syj脚本
> > > > 
> > > > 
> > > > 用了老版本确实可以了。你的宠汪汪赛跑可以助力吗。我用3月份的版本也不行
> > > 
> > > 
> > > 你现在用会赚京豆 会给其它的小号助力么 以前是只要没手动开过一次就开团失败 现在新版本每个号都给开过了 导致现在每个号都能开团 这样助力怎么都不够了
> > 
> > 
> > 可以，开团助力都正常
> 
> 我是说你现在用的话 会所有号都吃到助力么 如果所有号都开团的话 最终每个号都只能成功开到一次团吧 次数不够
日志没有完全看完，反正30个ck我只看了我的前5个号都是助力满了的，后面有没有不关心，哈哈哈

**Comment by limoruirui** [comment]
> > > > > > 不知道有没有办法拿到4月27号更新前的syj脚本
> > > > > 
> > > > > 
> > > > > 用了老版本确实可以了。你的宠汪汪赛跑可以助力吗。我用3月份的版本也不行
> > > > 
> > > > 
> > > > 你现在用会赚京豆 会给其它的小号助力么 以前是只要没手动开过一次就开团失败 现在新版本每个号都给开过了 导致现在每个号都能开团 这样助力怎么都不够了
> > > 
> > > 
> > > 可以，开团助力都正常
> > 
> > 
> > 我是说你现在用的话 会所有号都吃到助力么 如果所有号都开团的话 最终每个号都只能成功开到一次团吧 次数不够
> > 日志没有完全看完，反正30个ck我只看了我的前5个号都是助力满了的，后面有没有不关心，哈哈哈
 一个号可以开三次团的 按现在的情况 一次肯定是满的 就是不知道三次还能不能满  所有号都开团的话 肯定是不够的

**Comment by NewLife996** [comment]
> > 手动也不行，另外一个好像可以 在2021年05月09日 14:23，limo_ruirui 写道： 不知道有没有办法拿到4月27号更新前的syj脚本 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 手动也不行的号就是黑了 我感觉是脚本更新的问题 现在syj脚本是4月27号更新的 我就是那段时间开始不行的 而且之前在码云就有人提了 只不过没多久仓库就被封了 到这边感觉就没大佬看issue了 有时间我去找别人备份的更新前的脚本

兄弟，找到备份发我一份

**Comment by NewLife996** [comment]
> > 不知道有没有办法拿到4月27号更新前的syj脚本
> 
> 用了老版本确实可以了。你的宠汪汪赛跑可以助力吗。我用3月份的版本也不行

兄弟，你的老版本可以发我一份吗？

**Comment by NewLife996** [comment]
> > > > 手动也不行，另外一个好像可以 在2021年05月09日 14:23，limo_ruirui 写道： 不知道有没有办法拿到4月27号更新前的syj脚本 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > 
> > > 
> > > 手动也不行的号就是黑了 我感觉是脚本更新的问题 现在syj脚本是4月27号更新的 我就是那段时间开始不行的 而且之前在码云就有人提了 只不过没多久仓库就被封了 到这边感觉就没大佬看issue了 有时间我去找别人备份的更新前的脚本
> > 
> > 兄弟，找到备份发我一份
> 
> 遍地都是啊 docker官网一搜不就有一堆备份镜像么

好，我去找找看

**Comment by limoruirui** [comment]
> > > > > 手动也不行，另外一个好像可以 在2021年05月09日 14:23，limo_ruirui 写道： 不知道有没有办法拿到4月27号更新前的syj脚本 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > > 
> > > > 
> > > > 手动也不行的号就是黑了 我感觉是脚本更新的问题 现在syj脚本是4月27号更新的 我就是那段时间开始不行的 而且之前在码云就有人提了 只不过没多久仓库就被封了 到这边感觉就没大佬看issue了 有时间我去找别人备份的更新前的脚本
> > > 
> > > 
> > > 兄弟，找到备份发我一份
> > 
> > 
> > 遍地都是啊 docker官网一搜不就有一堆备份镜像么
> 
> 好，我去找找看

主要是我没在github上传过东西 不知道流程 感觉你去docker hub搜还快点

**Comment by NewLife996** [comment]
> > > > > > 手动也不行，另外一个好像可以 在2021年05月09日 14:23，limo_ruirui 写道： 不知道有没有办法拿到4月27号更新前的syj脚本 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > > > 
> > > > > 
> > > > > 手动也不行的号就是黑了 我感觉是脚本更新的问题 现在syj脚本是4月27号更新的 我就是那段时间开始不行的 而且之前在码云就有人提了 只不过没多久仓库就被封了 到这边感觉就没大佬看issue了 有时间我去找别人备份的更新前的脚本
> > > > 
> > > > 
> > > > 兄弟，找到备份发我一份
> > > 
> > > 
> > > 遍地都是啊 docker官网一搜不就有一堆备份镜像么
> > 
> > 好，我去找找看
> 
> 主要是我没在github上传过东西 不知道流程 感觉你去docker hub搜还快点

老哥直接发我邮箱吧，Newlife996@qq.com，谢谢啦

**Comment by limoruirui** [comment]
> > > > > > > 手动也不行，另外一个好像可以 在2021年05月09日 14:23，limo_ruirui 写道： 不知道有没有办法拿到4月27号更新前的syj脚本 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > > > > 
> > > > > > 
> > > > > > 手动也不行的号就是黑了 我感觉是脚本更新的问题 现在syj脚本是4月27号更新的 我就是那段时间开始不行的 而且之前在码云就有人提了 只不过没多久仓库就被封了 到这边感觉就没大佬看issue了 有时间我去找别人备份的更新前的脚本
> > > > > 
> > > > > 
> > > > > 兄弟，找到备份发我一份
> > > > 
> > > > 
> > > > 遍地都是啊 docker官网一搜不就有一堆备份镜像么
> > > 
> > > 
> > > 好，我去找找看
> > 
> > 
> > 主要是我没在github上传过东西 不知道流程 感觉你去docker hub搜还快点
> 
> 老哥直接发我邮箱吧，[Newlife996@qq.com](mailto:Newlife996@qq.com)，谢谢啦

晚上回去发你 刚下车

**Comment by NewLife996** [comment]
> > > > > > > > 手动也不行，另外一个好像可以 在2021年05月09日 14:23，limo_ruirui 写道： 不知道有没有办法拿到4月27号更新前的syj脚本 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > > > > > 
> > > > > > > 
> > > > > > > 手动也不行的号就是黑了 我感觉是脚本更新的问题 现在syj脚本是4月27号更新的 我就是那段时间开始不行的 而且之前在码云就有人提了 只不过没多久仓库就被封了 到这边感觉就没大佬看issue了 有时间我去找别人备份的更新前的脚本
> > > > > > 
> > > > > > 
> > > > > > 兄弟，找到备份发我一份
> > > > > 
> > > > > 
> > > > > 遍地都是啊 docker官网一搜不就有一堆备份镜像么
> > > > 
> > > > 
> > > > 好，我去找找看
> > > 
> > > 
> > > 主要是我没在github上传过东西 不知道流程 感觉你去docker hub搜还快点
> > 
> > 老哥直接发我邮箱吧，[Newlife996@qq.com](mailto:Newlife996@qq.com)，谢谢啦
> 
> 晚上回去发你 刚下车

好，谢谢老哥

**Comment by ryan016** [comment]
> 
> 晚上回去发你刚下车

赚京豆及宠汪汪的助力脚本也请给我发一份吧，谢谢！！honey.lover@qq.com

**Comment by ryan016** [comment]
> git checkout [commit] ./jd_syj.js

error: pathspec './jd_syj.js' did not match any file(s) known to git

**Comment by fuhuo8** [comment]
> > > > > > > > 手动也不行，另外一个好像可以 在2021年05月09日 14:23，limo_ruirui 写道： 不知道有没有办法拿到4月27号更新前的syj脚本 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > > > > > 
> > > > > > > 
> > > > > > > 手动也不行的号就是黑了 我感觉是脚本更新的问题 现在syj脚本是4月27号更新的 我就是那段时间开始不行的 而且之前在码云就有人提了 只不过没多久仓库就被封了 到这边感觉就没大佬看issue了 有时间我去找别人备份的更新前的脚本
> > > > > > 
> > > > > > 
> > > > > > 兄弟，找到备份发我一份
> > > > > 
> > > > > 
> > > > > 遍地都是啊 docker官网一搜不就有一堆备份镜像么
> > > > 
> > > > 
> > > > 好，我去找找看
> > > 
> > > 
> > > 主要是我没在github上传过东西 不知道流程 感觉你去docker hub搜还快点
> > 
> > 
> > 老哥直接发我邮箱吧，[Newlife996@qq.com](mailto:Newlife996@qq.com)，谢谢啦
> 
> 晚上回去发你 刚下车

老哥也来一份谢谢：fuhuo8@qq.com

**Comment by a131656** [comment]
> > > > > > > > 手动也不行，另外一个好像可以 在2021年05月09日 14:23，limo_ruirui 写道： 不知道有没有办法拿到4月27号更新前的syj脚本 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > > > > > > 
> > > > > > > 
> > > > > > > 手动也不行的号就是黑了 我感觉是脚本更新的问题 现在syj脚本是4月27号更新的 我就是那段时间开始不行的 而且之前在码云就有人提了 只不过没多久仓库就被封了 到这边感觉就没大佬看issue了 有时间我去找别人备份的更新前的脚本
> > > > > > 
> > > > > > 
> > > > > > 兄弟，找到备份发我一份
> > > > > 
> > > > > 
> > > > > 遍地都是啊 docker官网一搜不就有一堆备份镜像么
> > > > 
> > > > 
> > > > 好，我去找找看
> > > 
> > > 
> > > 主要是我没在github上传过东西 不知道流程 感觉你去docker hub搜还快点
> > 
> > 
> > 老哥直接发我邮箱吧，[Newlife996@qq.com](mailto:Newlife996@qq.com)，谢谢啦
> 
> 晚上回去发你 刚下车

老哥能来一份吗1316563150@qq.com😊

**Comment by lostme01** [comment]
请问这个脚本找到了 替换

**Comment by limoruirui** [comment]
20号的版本不能正常开团 用前天12号更新的版本可以正常助力了 更新就行

**Comment by lhc13145** [comment]
> 20号的版本不能正常开团 用前天12号更新的版本可以正常助力了 更新就行

有那个版本怎么替换呢？那些命令不会

**Comment by limoruirui** [comment]
> > 20号的版本不能正常开团 用前天12号更新的版本可以正常助力了 更新就行
> 
> 有那个版本怎么替换呢？那些命令不会

20号的版本已经用不了了 用现在最新的就行 替换的话 定时任务参考其他脚本的格式设置一下 然后把脚本用yml挂在进去就行了 不会挂载的话 就直接扔进宿主机的logs文件夹里 然后你就能在容器里的logs文件夹里看到了

**Comment by lostme01** [comment]
现在新版每天都领取80豆但是开团不能助力，每天助力人数都是0

**Comment by limoruirui** [comment]
> 现在新版每天都领取80豆但是开团不能助力，每天助力人数都是0

你可以看看脚本文件日期 我的是5月12号的 正常开团 正常助力
