### ISSUE TITLE
telegram发送通知消息失败！！

### ISSUE THREAD

**Issue by dzpbb** [wisz2021/jd_docker#114]
HTTPError: Response code 400 (Bad Request)
    at Request.<anonymous> (/scripts/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: undefined,
  timings: {
    start: 1620502589325,
    socket: 1620502589326,
    lookup: 1620502589330,
    connect: 1620502589332,
    secureConnect: 1620502591766,
    upload: 1620502591767,
    response: 1620502592435,
    end: 1620502592436,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 4,
      tcp: 2,
      tls: 2434,
      request: 1,
      firstByte: 668,
      download: 1,
      total: 3111
    }
  }
}

**Comment by ChellyL** [comment]
我也是，发送/node指令没反应

**Comment by kusiru** [comment]
没写代理？

**Comment by wisz2021** [comment]
账号太多。通知文本长度过长？

**Comment by xjw00654** [comment]
> 账号太多。通知文本长度过长？

我27个账号也遇到这种情况，但是例如cookie过期那种短消息倒是能推送成功，估计是文本太长导致的

![image](https://user-images.githubusercontent.com/24971464/117909273-8490e580-b30c-11eb-98a9-9c8ff095df1b.png)
![image](https://user-images.githubusercontent.com/24971464/117909250-7773f680-b30c-11eb-8618-44c0d7ef1096.png)
