### ISSUE TITLE
大佬，你好，经常出现如下错误，请问怎么解决？

### ISSUE THREAD

**Issue by aliyy2021** [wisz2021/jd_docker#151]
events.js:292

      throw er; // Unhandled 'error' event

      ^

Error: Unexpected server response: 504

    at ClientRequest.<anonymous> (/scripts/node_modules/ws/lib/websocket.js:604:7)

    at ClientRequest.emit (events.js:315:20)

    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:641:27)

    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)

    at TLSSocket.socketOnData (_http_client.js:509:22)

    at TLSSocket.emit (events.js:315:20)

    at addChunk (internal/streams/readable.js:309:12)

    at readableAddChunk (internal/streams/readable.js:284:9)

    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)

    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)

Emitted 'error' event on WebSocket instance at:

    at abortHandshake (/scripts/node_modules/ws/lib/websocket.js:732:15)

    at ClientRequest.<anonymous> (/scripts/node_modules/ws/lib/websocket.js:604:7)

    [... lines matching original stack trace ...]

    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)

crond[49]: USER root pid 29000 cmd sleep $((RANDOM % $RANDOM_DELAY_MAX));  . /scripts/docker/auto_help.sh export > /scripts/logs/auto_help_export.log && node  /scripts/jd_dreamFactory.js |ts >> /scripts/logs/jd_dreamFactory.log 2>&1

**Comment by wisz2021** [comment]
我也不知。
