### ISSUE TITLE
金融养猪脚本执行报错

### ISSUE THREAD

**Issue by BlueSpiderGIGI** [wisz2021/jd_docker#176]
❗️金融养猪, 错误!
TypeError: Cannot read property 'name' of undefined
    at /scripts/jd_pigPet.js:258:117
    at got.post.then.message (/scripts/jd_pigPet.js:709:5772)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
第5天已签到
开宝箱失败:宝箱次数上限
当前大转盘剩余免费抽奖次数：：1
浏览一次锦鲤活动未完成
浏览京喜工厂活动未完成
浏览东东农场未完成
浏览宠汪汪未完成
查看更多趣味游戏未完成
为自己充1笔话费未完成
一分获取话费福利未完成
小金库还信用卡未完成
超省免息购好物未完成
逛逛吃货嘉年华未完成
花金贴兑权益未完成
报名理财课得猪粮未完成
逛逛进口吃货节未完成
去京东到家签到未完成
购买黄金产品未完成
去领金贴页面签到未完成
分期购好物未完成
浏览种豆得豆活动未完成
浏览京喜财富岛活动未完成
浏览京喜农场页面未完成
浏览金融签到活动未完成
浏览天天提鹅活动未完成
完成每日分享已领取

**Comment by lockingxp** [comment]
这个不要问了 老大说做不了
