### ISSUE TITLE
telegram通知失败

### ISSUE THREAD

**Issue by WinterBoring** [wisz2021/jd_docker#185]
telegram发送通知消息失败！！

RequestError: getaddrinfo EAI_AGAIN api.telegram.org
    at ClientRequest.<anonymous> (/jd/scripts/node_modules/got/dist/source/core/index.js:953:111)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/jd/scripts/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26) {
  code: 'EAI_AGAIN',
  timings: {
    start: 1621053820393,
    socket: 1621053820398,
    lookup: 1621053825403,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1621053825408,
    abort: undefined,
    phases: {
      wait: 5,
      dns: 5005,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 5015
    }
  }
}每次都显示通知失败！参数设置多次检查没问题，节点翻墙正常，并且换了四五个节点测试还是一样，容器，镜像删除，拉取重装五次以上，还是同样问题！请大佬帮忙看看，是什么原因！谢谢

**Comment by yanglili5** [comment]
据说是你的服务器也要连接外网 才可以用TG,

**Comment by WinterBoring** [comment]
> 据说是你的服务器也要连接外网才可以用TG，

外网是对的啊！交互功能。docker上其他容器连接网络也是正常的。之前也是正常通知的

**Comment by wisz2021** [comment]
这种 问题 ，应该是节点问题。 

你换节点看看吧， 或者看clash日志？  如果是搭建clash的

**Comment by ryan016** [comment]
> 这种 问题 ，应该是节点问题。
> 
> 你换节点看看吧， 或者看clash日志？ 如果是搭建clash的

我这边是除了jd_bean_change这个脚本tg推送失败外，其他脚本的tg推送都正常

**Comment by fengmikaelson** [comment]
> 这种 问题 ，应该是节点问题。
> 
> 你换节点看看吧， 或者看clash日志？ 如果是搭建clash的
大佬这个是什么原因？其他都能推送，就这个签到的不行。。。其他的一些红包雨什么的都会推过来。
![image](https://user-images.githubusercontent.com/10394327/118600802-0dfc5800-b7e4-11eb-8466-bd87beb45b62.png)

**Comment by litepi** [comment]
telegram发送通知消息失败！！

HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (/scripts/node_modules/got/dist/source/as-promise/ind                                                                                        ex.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: undefined,
  timings: {
    start: 1621369557378,
    socket: 1621369557379,
    lookup: 1621369557386,
    connect: 1621369557638,
    secureConnect: 1621369557894,
    upload: 1621369557894,
    response: 1621369558148,
    end: 1621369558149,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 7,
      tcp: 252,
      tls: 256,
      request: 0,
      firstByte: 254,
      download: 1,
      total: 771
    }
  }
}
