### ISSUE TITLE
jd_bean_sign 自动执行异常

### ISSUE THREAD

**Issue by start0325** [wisz2021/jd_docker#19]
```
Apr 29 00:05:20 *************开始京东账号1 京豆签到*******************
Apr 29 00:05:20
Apr 29 00:05:20 开始替换变量
Apr 29 00:05:20 替换变量完毕
Apr 29 00:05:20
Apr 29 00:05:20 开始执行脚本签到，请稍等
Apr 29 00:05:20 京东签到脚本执行异常:Error: Command failed: /usr/bin/node ./JD_DailyBonus.js >> ./result.txt
Apr 29 00:05:20 internal/modules/cjs/loader.js:818
Apr 29 00:05:20 throw err;
Apr 29 00:05:20 ^
Apr 29 00:05:20
Apr 29 00:05:20 Error: Cannot find module 'request'
Apr 29 00:05:20 Require stack:
Apr 29 00:05:20 - /root/JD_DailyBonus.js
Apr 29 00:05:20 at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
Apr 29 00:05:20 at Function.Module._load (internal/modules/cjs/loader.js:667:27)
Apr 29 00:05:20 at Module.require (internal/modules/cjs/loader.js:887:19)
Apr 29 00:05:20 at require (internal/modules/cjs/helpers.js:74:18)
Apr 29 00:05:20 at /root/JD_DailyBonus.js:2203:23
Apr 29 00:05:20 at nobyda (/root/JD_DailyBonus.js:2212:5)
Apr 29 00:05:20 at Object.<anonymous> (/root/JD_DailyBonus.js:104:15)
Apr 29 00:05:20 at Module._compile (internal/modules/cjs/loader.js:999:30)
Apr 29 00:05:20 at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
Apr 29 00:05:20 at Module.load (internal/modules/cjs/loader.js:863:32) {
Apr 29 00:05:20 code: 'MODULE_NOT_FOUND',
Apr 29 00:05:20 requireStack: [ '/root/JD_DailyBonus.js' ]
Apr 29 00:05:20 }
Apr 29 00:05:20
Apr 29 00:05:20
Apr 29 00:05:20 🔔京东多合一签到, 结束! 🕛 15.692 秒
Apr 29 00:05:20
```

**Comment by start0325** [comment]
> 
> 
> 缺少request依赖包

使用的是 您的默认教程 docker-compose，按理说依赖都是镜像自动安装完成的，怎么会缺少呢？
这个问题大概最近一周左右开始出现，以前用很久都没问题。
而且通过 bot 手动执行的时候是不报错的，只在自动 crond 的时候出现，很诡异。

**Comment by start0325** [comment]
已解决
