### ISSUE TITLE
京喜工厂物品完成后没有通知。

### ISSUE THREAD

**Issue by nepally** [wisz2021/jd_docker#209]
大佬，更新镜像后发现京喜工厂物品完成后没有通知推送。

**Comment by Hhhr99** [comment]
images id：160a62df5141 我的推送没问题

**Comment by nepally** [comment]
京喜工厂推送有开关吗？

**Comment by wisz2021** [comment]
物品完成后，4小时通知一次 。也就是  0点  ，4点，8点。12点。16点，........等等

**Comment by wisz2021** [comment]
> 京喜工厂推送有开关吗？

没有开关

**Comment by nepally** [comment]
大佬，早上又测试了下，8点没有京喜工厂的通知推送。
![京喜1](https://user-images.githubusercontent.com/80736651/118738269-34b89e00-b879-11eb-9f72-7f962276e179.png)
![京喜2_副本](https://user-images.githubusercontent.com/80736651/118738515-d93ae000-b879-11eb-81b9-93ff1355ac6d.jpg)

**Comment by nepally** [comment]
京喜工厂Logs文件错误提示
May 19 10:50:56 TypeError: Cannot destructure property 'componentList' of 'GetUserComponentRes.data' as it is undefined.
May 19 10:50:56     at PickUp (/scripts/jd_dreamFactory.js:741:13)
May 19 10:50:56     at processTicksAndRejections (internal/process/task_queues.js:97:5)
May 19 10:50:56     at async jdDreamFactory (/scripts/jd_dreamFactory.js:144:5)
May 19 10:50:56     at async /scripts/jd_dreamFactory.js:95:7

**Comment by zero205** [comment]
> 京喜工厂Logs文件错误提示
> May 19 10:50:56 TypeError: Cannot destructure property 'componentList' of 'GetUserComponentRes.data' as it is undefined.
> May 19 10:50:56 at PickUp (/scripts/jd_dreamFactory.js:741:13)
> May 19 10:50:56 at processTicksAndRejections (internal/process/task_queues.js:97:5)
> May 19 10:50:56 at async jdDreamFactory (/scripts/jd_dreamFactory.js:144:5)
> May 19 10:50:56 at async /scripts/jd_dreamFactory.js:95:7

+1，同样的错误
