### ISSUE TITLE
一直报这个错误，

### ISSUE THREAD

**Issue by wander555** [wisz2021/jd_docker#23]
![1111](https://user-images.githubusercontent.com/6134211/116635284-f2462480-a990-11eb-8753-3d2ebdda1fc8.png)

群晖docker

**Comment by lockingxp** [comment]
去看issue#15

**Comment by xiaokaixuan** [comment]
> ![1111](https://user-images.githubusercontent.com/6134211/116635284-f2462480-a990-11eb-8753-3d2ebdda1fc8.png)
> 
> 群晖docker

#5

**Comment by boluosaibei** [comment]
一样
/scripts/jd_health_collect.js:79

if (data?.data?.bizCode === 0) {

^


SyntaxError: Unexpected token '.'

at wrapSafe (internal/modules/cjs/loader.js:915:16)

at Module._compile (internal/modules/cjs/loader.js:963:27)

at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

at Module.load (internal/modules/cjs/loader.js:863:32)

at Function.Module._load (internal/modules/cjs/loader.js:708:14)

at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)

at internal/main/run_main_module.js:17:47

**Comment by xiaokaixuan** [comment]
@boluosaibei 更新镜像 参见 #5
