### ISSUE TITLE
美丽研究院脚本 每次需要先打开jd app的美丽研究院才能正常跑

### ISSUE THREAD

**Issue by wspzf** [wisz2021/jd_docker#230]
JD_USER_AGENT已经自定义
每次自动任务都会报图片类似的错误
![image](https://user-images.githubusercontent.com/43857401/118751871-a81bd900-b894-11eb-9440-c8de1d7437dc.png)

打开jd app的美丽研究院后再手动跑就正常了

**Comment by BlueSpiderGIGI** [comment]
我跟你报错内容不一样
美丽研究院 API请求失败，请检查网路重试
提示：请尝试换服务器ip或者设置"xinruimz-isv.isvjcloud.com"域名直连，或者自定义UA再次尝试(环境变量JD_USER_AGENT)

**Comment by BIGBbox** [comment]
我用tg的spnode跑得时候报这个错

 ↓↓↓ spnode /scripts/jd_beauty.js 执行结果 ↓↓↓ 


/scripts/jd_beauty.js:324
            console.log(`【${vo?.data?.position}】上正在生产【${vo?.data?.material_name}】，可收取 ${vo.data.produce_num} 份`)
                               ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at 

自动执行的日志文件里只有这两行

**May 19 07:41:41 
May 19 12:41:30**

**Comment by kongren978** [comment]
巧了我也是

**Comment by kongren978** [comment]
想问大佬们
请尝试换服务器ip或者设置"xinruimz-isv.isvjcloud.com"域名直连，或者自定义UA再次尝试(环境变量JD_USER_AGENT)
怎么设置来个吊大的

**Comment by wspzf** [comment]
> 我跟你报错内容不一样
> 美丽研究院 API请求失败，请检查网路重试
> 提示：请尝试换服务器ip或者设置"xinruimz-isv.isvjcloud.com"域名直连，或者自定义UA再次尝试(环境变量JD_USER_AGENT)

你这个需要更改JD_USER_AGENT，手机抓包app的UA

**Comment by wspzf** [comment]
s
