### ISSUE TITLE
东东萌宠报错

### ISSUE THREAD

**Issue by kongren9** [wisz2021/jd_docker#236]
May 19 18:36:23 东东萌宠: API查询请求失败 ‼️‼️
May 19 18:36:23 "getaddrinfo EAI_AGAIN api.m.jd.com"
May 19 18:36:23 
May 19 18:36:23 ❗️东东萌宠, 错误!
May 19 18:36:23 
May 19 18:36:23 
May 19 18:36:23 ❗️东东萌宠, 错误!
May 19 18:36:23 TypeError: Cannot read property 'resultCode' of undefined
May 19 18:36:23     at jdPet (/scripts/jd_pet.js:125:22)
May 19 18:36:23     at processTicksAndRejections (internal/process/task_queues.js:95:5)
May 19 18:36:23     at async /scripts/jd_pet.js:72:7

**Comment by zlhdd108** [comment]
同样的报错，而且“东东工厂”也有报错：
![image](https://user-images.githubusercontent.com/16465666/118903138-a3fdc300-b949-11eb-8194-82b9d37bca45.png)
