### ISSUE TITLE
京喜工厂报错，物品完成无推送。

### ISSUE THREAD

**Issue by nepally** [wisz2021/jd_docker#240]
京喜工厂Logs文件错误提示
May 19 10:50:56 TypeError: Cannot destructure property 'componentList' of 'GetUserComponentRes.data' as it is undefined.
May 19 10:50:56 at PickUp (/scripts/jd_dreamFactory.js:741:13)
May 19 10:50:56 at processTicksAndRejections (internal/process/task_queues.js:97:5)
May 19 10:50:56 at async jdDreamFactory (/scripts/jd_dreamFactory.js:144:5)
May 19 10:50:56 at async /scripts/jd_dreamFactory.js:95:7

**Comment by nepally** [comment]
May 20 14:51:20 ******开始【京东账号1】*********
May 20 14:51:20 
May 20 14:51:20 再加7.03%电力可开红包
May 20 14:51:20 
May 20 14:51:20 当前电力：15
May 20 14:51:20 当前等级：8
May 20 14:51:20 
May 20 14:51:20 【京东账号1（）的京喜工厂好友互助码】
May 20 14:51:20 已投入电力：224800
May 20 14:51:20 所需电力：320000
May 20 14:51:20 生产进度：70.25%
May 20 14:51:20 预计最快还需 【0.55天】生产完毕
May 20 14:51:20 你今日还能帮好友打工（0/3）次
May 20 14:51:20 【今日招工进度】6/14
May 20 14:51:20 今日助力好友机会已耗尽
May 20 14:51:20 发电机：当前 360.8 电力，最大值 510 电力
May 20 14:51:20 本次发电机电力集满分享后不可获得双倍电力，故现在收取电力
May 20 14:51:20 收取电力成功: 共361 
May 20 14:51:20 去做任务：4元抢超能洗衣液
May 20 14:51:21 做任务完成！
May 20 14:51:21 领取4元抢超能洗衣液任务奖励成功，收获：300电力
May 20 14:51:22 去做任务：4元抢超能洗衣液
May 20 14:51:22 DoTask异常：{"data":{"awardStatus":1,"completedTimes":1,"dateTypeExtra":"20210520","updateTime":1621493485,"userStatusConfigExtra":""},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":1009}
May 20 14:51:22 领取4元抢超能洗衣液任务奖励失败，任务已领奖
May 20 14:51:23 完成任务：共领取661电力
May 20 14:51:23 成功投入电力600电力
May 20 14:51:25 
May 20 14:51:25 ❗️京喜工厂, 错误!
May 20 14:51:25 TypeError: Cannot destructure property 'componentList' of 'GetUserComponentRes.data' as it is undefined.
May 20 14:51:25     at PickUp (/scripts/jd_dreamFactory.js:741:13)
May 20 14:51:25     at processTicksAndRejections (internal/process/task_queues.js:97:5)
May 20 14:51:25     at async jdDreamFactory (/scripts/jd_dreamFactory.js:144:5)
May 20 14:51:25     at async /scripts/jd_dreamFactory.js:95:7

**Comment by acoolbook** [comment]
我的是没报错，但是部分账户生产完成不推送
