### ISSUE TITLE
❗️京喜签到, 错误!

### ISSUE THREAD

**Issue by piaoyun** [wisz2021/jd_docker#254]
TypeError: data.data.tasks is not iterable
    at /jd/scripts/jx_sign.js:121:38
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jx_sign.js:315:4869)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
任务完成失败，错误信息not sign

**Comment by dongjun613** [comment]
+1

**Comment by lyiangsh** [comment]
+1

**Comment by lyiangsh** [comment]
> 
> 
> TypeError: data.data.tasks is not iterable
> at /jd/scripts/jx_sign.js:121:38
> at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jx_sign.js:315:4869)
> at processTicksAndRejections (internal/process/task_queues.js:93:5)
> 任务完成失败，错误信息not sign

是不是用的青龙
