### ISSUE TITLE
运行报错，看不出哪个脚本报错

### ISSUE THREAD

**Issue by zcjschina** [wisz2021/jd_docker#284]
events.js:353
      throw er; // Unhandled 'error' event
      ^
Error: Unexpected server response: 504
    at ClientRequest.<anonymous> (/scripts/node_modules/ws/lib/websocket.js:604:7)
    at ClientRequest.emit (events.js:376:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)
Emitted 'error' event on WebSocket instance at:
    at abortHandshake (/scripts/node_modules/ws/lib/websocket.js:732:15)
    at ClientRequest.<anonymous> (/scripts/node_modules/ws/lib/websocket.js:604:7)
    [... lines matching original stack trace ...]
    at TLSSocket.Readable.push (internal/streams/readable.js:223:10)

**Comment by lhc13145** [comment]
太难了，cookie获取好像不行了啊，bot都找不到
