### ISSUE TITLE
东东农场东东萌宠异常

### ISSUE THREAD

**Issue by lhc13145** [wisz2021/jd_docker#304]
脚本运行异常如何解决   ❗️东东萌宠, 错误!
May 25 06:37:50 TypeError: Cannot read property 'code' of undefined
May 25 06:37:50     at jdPet (/scripts/jd_pet.js:90:24)
May 25 06:37:50     at processTicksAndRejections (internal/process/task_queues.js:95:5)
May 25 06:37:50     at async /scripts/jd_pet.js:72:7

**Comment by anakinlee99** [comment]
我的也是，昨天开始出现的。

日志如下，大佬们有空帮忙看一下呀。

东东萌宠: API查询请求失败 ‼️‼️
"connect ETIMEDOUT 116.198.168.64:443"

❗️东东萌宠, 错误!


❗️东东萌宠, 错误!
TypeError: Cannot read property 'code' of undefined
    at slaveHelp (/jd/scripts/jd_pet.js:286:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async jdPet (/jd/scripts/jd_pet.js:132:7)
    at async /jd/scripts/jd_pet.js:72:7
