### ISSUE TITLE
动物联盟出现如下错误

### ISSUE THREAD

**Issue by aliyy2021** [wisz2021/jd_docker#317]
crond[70]: crond (busybox 1.31.1) started, log level 8

crond[70]: USER root pid  71 cmd sleep $((RANDOM % $RANDOM_DELAY_MAX));  . /scripts/docker/auto_help.sh export > /scripts/logs/auto_help_export.log && node  /scripts/jd_city.js |ts >> /scripts/logs/jd_city.log 2>&1

crond[70]: USER root pid  72 cmd sleep $((RANDOM % $RANDOM_DELAY_MAX));  . /scripts/docker/auto_help.sh export > /scripts/logs/auto_help_export.log && node  /scripts/jd_zoo.js |ts >> /scripts/logs/jd_zoo.log 2>&1

crond[70]: USER root pid 423 cmd . /scripts/docker/auto_help.sh export > /scripts/logs/auto_help_export.log && node  /scripts/jd_joy_feedPets.js |ts >> /scripts/logs/jd_joy_feedPets.log 2>&1

(node:411) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'produceScore' of undefined

    at dealReturn (/scripts/jd_zoo.js:530:49)

    at /scripts/jd_zoo.js:493:9

    at got.post.then.message (/scripts/jd_zoo.js:971:5772)

    at runMicrotasks (<anonymous>)

    at processTicksAndRejections (internal/process/task_queues.js:95:5)

(Use `node --trace-warnings ...` to show where the warning was created)

(node:411) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

(node:411) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

crond[70]: USER root pid 1120 cmd sleep $((RANDOM % $RANDOM_DELAY_MAX));  . /scripts/docker/auto_help.sh export > /scripts/logs/auto_help_export.log && node  /scripts/jd_bookshop.js |ts >> /scripts/logs/jd_bookshop.log 2>&1

**Comment by lee-yuanchun** [comment]
这个问题解决了吗  我也是一直报这个错误

**Comment by lee-yuanchun** [comment]
貌似是这个活动把账号暂时黑了 ，   不知道要黑多久。。。。。。。。。。。。。

**Comment by aliyy2021** [comment]
没解决，今天连任务都不做了，日志提示火爆，手动又可以做
