### ISSUE TITLE
京东618任务执行有时候会报错如下，希望修复一下，如果报错应该跳过该账号，否则直接终止脚本执行了！

### ISSUE THREAD

**Issue by niuxvdong** [wisz2021/jd_docker#329]
已签到
/jd/scripts/jd_zoo.js:553
        console.log(`收取成功，获得：${data.data.result.produceScore}`);
                                                ^

TypeError: Cannot read property 'produceScore' of undefined
    at dealReturn (/jd/scripts/jd_zoo.js:553:49)
    at /jd/scripts/jd_zoo.js:514:9
    at got.post.then.message (/jd/scripts/jd_zoo.js:1028:5772)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

**Comment by JiZhi-Error** [comment]
+1 我也遇到了，希望修复
