### ISSUE TITLE
京喜签到错误

### ISSUE THREAD

**Issue by qsls9** [wisz2021/jd_docker#335]
❗️京喜签到, 错误!
TypeError: data.data.tasks is not iterable
    at /jd/scripts/jx_sign.js:121:38
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/jd/scripts/jx_sign.js:315:4869)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
任务完成失败，错误信息not sign

找不到这个对象了，是签到的返回字段更新了吗。

**Comment by MapleStoryXiaoA** [comment]
是的, 我也报错了

**Comment by lockingxp** [comment]
任务没有了啊 去app看看
