### ISSUE TITLE
docker logs里有两个js一直报这个错SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by VergLsm** [wisz2021/jd_docker#41]
```
/scripts/jd_health_collect.js:79
					if (data?.data?.bizCode === 0) {
					         ^
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47


/scripts/jd_market_lottery.js:94
          let taskList = data?.activityData?.floorList?.filter(vo=>vo.template==='score_task')[0]
                              ^
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by LongxianShi** [comment]
5月1日前的镜像重新pull一次，大大已经把nodejs升级了

**Comment by VergLsm** [comment]
pull出新问题了，现在连容器都启动不了😂
```
npm install 安装最新依赖


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0xbeb4b12c
Illegal instruction (core dumped)
```

**Comment by hh2115** [comment]
我也遇到这个问题了，你解决了吗
