### ISSUE TITLE
jd_bean_change使用pushplus推送出错

### ISSUE THREAD

**Issue by lxr760** [wisz2021/jd_docker#56]
push+发送一对多通知消息失败！！

HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/jd/scripts/node_modules/got/dist/source/as-promise/index.js:117:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: undefined,
  timings: {
    start: 1619971227308,
    socket: 1619971227310,
    lookup: 1619971227311,
    connect: 1619971227331,
    secureConnect: undefined,
    upload: 1619971227331,
    response: 1619971227355,
    end: 1619971227584,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 1,
      tcp: 20,
      tls: undefined,
      request: 0,
      firstByte: 24,
      download: 229,
      total: 276
    }
  }
}

**Comment by scjean** [comment]
我也是用的push+群组推送，没有问题，需要订阅人。

**Comment by yang7758258** [comment]
一样的情况，解决了吗，兄弟

**Comment by C-racker** [comment]
+1 我用的是 server酱
