### ISSUE TITLE
美丽研究院报错，有一样的么？

### ISSUE THREAD

**Issue by kissfast** [wisz2021/jd_docker#59]
当期活动：美妆馆日常
仓库信息:【油脂】1份 【乳化剂】51份 【保湿剂】643份 【滑石粉】677份 【树脂】594份 【滋润剂】342份 【香料】263份 
任务完成成功，获得100美妆币
收取产品失败，错误信息action not exists
收取产品失败，错误信息action not exists
仓库信息:【油脂】1份 【乳化剂】51份 【保湿剂】643份 【滑石粉】677份 【树脂】594份 【滋润剂】342份 【香料】263份 
========可生产商品信息========
生产【腮红】需要原料【滑石粉】1 份 （库存 677 份）【颜料】3 份 (没有库存)【香料】2 份 （库存 263 份）
【腮红】原料不足，无法生产
生产【乳液】需要原料【矿物质水】1 份 (没有库存)【保湿剂】1 份 （库存 643 份）【滋润剂】3 份 （库存 342 份）
【乳液】原料不足，无法生产
生产【指甲油】需要原料【树脂】2 份 （库存 594 份）【颜料】4 份 (没有库存)
【指甲油】原料不足，无法生产
=======================
========原料生产信息========
(node:26161) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'material_name' of undefined
    at WebSocket.client.onmessage (/jd/scripts/jd_beauty.js:258:23)
    at WebSocket.onMessage (/jd/scripts/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/jd/scripts/node_modules/ws/lib/websocket.js:835:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/jd/scripts/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/jd/scripts/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/jd/scripts/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/jd/scripts/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:26161) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:26161) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:26161) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'material_name' of undefined
    at WebSocket.client.onmessage (/jd/scripts/jd_beauty.js:258:23)
    at WebSocket.onMessage (/jd/scripts/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/jd/scripts/node_modules/ws/lib/websocket.js:835:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/jd/scripts/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/jd/scripts/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/jd/scripts/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/jd/scripts/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
(node:26161) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:26161) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'material_name' of undefined
    at WebSocket.client.onmessage (/jd/scripts/jd_beauty.js:258:23)
    at WebSocket.onMessage (/jd/scripts/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/jd/scripts/node_modules/ws/lib/websocket.js:835:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/jd/scripts/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/jd/scripts/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/jd/scripts/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/jd/scripts/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
(node:26161) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:26161) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'material_name' of undefined
    at WebSocket.client.onmessage (/jd/scripts/jd_beauty.js:258:23)
    at WebSocket.onMessage (/jd/scripts/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/jd/scripts/node_modules/ws/lib/websocket.js:835:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/jd/scripts/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/jd/scripts/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/jd/scripts/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/jd/scripts/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
(node:26161) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:26161) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'material_name' of undefined
    at WebSocket.client.onmessage (/jd/scripts/jd_beauty.js:258:23)
    at WebSocket.onMessage (/jd/scripts/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/jd/scripts/node_modules/ws/lib/websocket.js:835:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/jd/scripts/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/jd/scripts/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/jd/scripts/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/jd/scripts/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
(node:26161) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:26161) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'material_name' of undefined
    at WebSocket.client.onmessage (/jd/scripts/jd_beauty.js:258:23)
    at WebSocket.onMessage (/jd/scripts/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/jd/scripts/node_modules/ws/lib/websocket.js:835:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/jd/scripts/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/jd/scripts/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/jd/scripts/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/jd/scripts/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
(node:26161) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:26161) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'describe' of undefined
    at WebSocket.client.onmessage (/jd/scripts/jd_beauty.js:384:39)
    at WebSocket.onMessage (/jd/scripts/node_modules/ws/lib/event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (/jd/scripts/node_modules/ws/lib/websocket.js:835:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (/jd/scripts/node_modules/ws/lib/receiver.js:437:14)
    at Receiver.getData (/jd/scripts/node_modules/ws/lib/receiver.js:367:17)
    at Receiver.startLoop (/jd/scripts/node_modules/ws/lib/receiver.js:143:22)
    at Receiver._write (/jd/scripts/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
(node:26161) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)

**Comment by YoYulyvW** [comment]
一样

**Comment by fuhuo8** [comment]
一样

**Comment by c526796017** [comment]
老哥，请问下我这边美丽研究院一直403，请问你那边碰到过吗，如果碰到过是怎么解决的呢？

**Comment by kissfast** [comment]
> 老哥，请问下我这边美丽研究院一直403，请问你那边碰到过吗，如果碰到过是怎么解决的呢？

你看日志最后一行的提示，说的很清楚了，照着做就行了

**Comment by c526796017** [comment]
> > 老哥，请问下我这边美丽研究院一直403，请问你那边碰到过吗，如果碰到过是怎么解决的呢？
> 
> 你看日志最后一行的提示，说的很清楚了，照着做就行了

日志最后一行是说设置域名直连，但是百度了很久也没看到怎么设置域名直连，容器内外直接ping那个域名是没有问题的，请教下老哥怎么设置。。

**Comment by Deng-TR** [comment]
接口更新了，自己抓下包，修改对应接口地址就行了
